version: '3.5'

services:

  todo-db:
    image: postgres:14
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=todouser
     - POSTGRES_PASSWORD=todopw
     - POSTGRES_DB=tododb
    volumes:
     - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
     - my-network
networks:
  my-network:
    name: todo-network
